<a href="https://colab.research.google.com/github/sasachichito/knowledge/blob/master/computer/%E8%87%AA%E7%84%B6%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86_%E3%82%BC%E3%83%AD%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%E5%88%86%E9%A1%9E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 依存関係

In [1]:
!pip install transformers[ja]

from urllib.request import urlopen
from bs4 import BeautifulSoup

def webpage_to_text(url, selector):
  text = ''
  with urlopen(url) as res:
      html = res.read().decode('UTF-8', 'ignore')
      soup = BeautifulSoup(html, 'html.parser')
      # article = soup.find('div', class_="articleBody")
      # text = article.get_text(strip=True)
      article = soup.select(selector)
      text = ''
      for p in article:
        text += p.get_text(strip=True)
      return text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 600.9/600.9 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 37.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 25.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 MB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.5 MB/s eta 0:00:00
  Created wheel for ipadic: filename=ipadic-1.0.0-py3-none-any.whl size=13556704 sha256=d2885ca04cfab28285e77f8e70b47661f457d2739c9a4a2608837ce7966bb66b
  Stored in directory: /root/.cache/pip/wheels/5b/ea/e3/2f6e0860a327daba3b030853fce4483ed37468bbf1101c59c3
  Created wheel for unidic: filename=unidic-1.1.0-py3-none-any.whl size=7406 sha256=bd0b18b8e7ce738c4ce3a99f0ec162c846a5344d199ba4af28a

# ゼロショット分類ライブラリ比較

In [3]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1

classifier_mDeBERT = pipeline("zero-shot-classification",model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7", device=device)
texts = ["今日、新しいiPhoneが発売されました"]
labels = ["スマートフォン", "エンタメ", "スポーツ"]
result_md = classifier_mDeBERT(texts, labels, hypothesis_template="このニュースは{}に関する文章です.")
print(result_md)

classifier_bart = pipeline("zero-shot-classification",model="facebook/bart-large-mnli", device=device)
texts = ["Darth Vader"]
labels = ["Star Wars", "Star Trek"]
result_b = classifier_bart(texts, labels, hypothesis_template="This person is in {}.")
print(result_b)

[{'sequence': '今日、新しいiPhoneが発売されました', 'labels': ['スマートフォン', 'エンタメ', 'スポーツ'], 'scores': [0.9712119102478027, 0.023089371621608734, 0.00569870974868536]}]
[{'sequence': 'Darth Vader', 'labels': ['Star Wars', 'Star Trek'], 'scores': [0.9938298463821411, 0.006170147098600864]}]


パイプラインから実行(日本語)

In [20]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1
classifier_mDeBERT = pipeline("zero-shot-classification",model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7", device=device)

sentence = 'HOME/AINOW編集部/Google I/O 2024におけるAI発表まとめ#Gemini#Google I/O#特集記事2024.05.28Google I/O 2024におけるAI発表まとめ最終更新日：2024年5月28日Google I/O 2024基調講演に登場したスンダ―・ピチャイGoogle CEO。画像出典：Googleブログ記事目次はじめにサマリーGeminiファミリーのアップデートとその活用軽量な1.5 Flash、アップデートしたGemini 1.5 Pro、先進的なProject Astraさらに多機能になる生成検索Gemini 1.5 Proをフル活用するGemini for Google Workspaceその他のGemini活用アプリAIによるAndroidの進化クリエイティブAIの進化ImageFXとImagen 3MusicFXと音楽業界とのコラボレーションVideoFXとVeoVeoとSoraの違い4人のアーティストと「不思議の国のアリス」を生成AIで再構築AI開発者のためのAIGemma 2とPaliGemmaデロリアンが授与されるGemini API デベロッパーコンペティション多数のAI開発ツールが発表＆アップデート第6世代AI用ハードウェア「Trillium」責任あるAIの取り組み拡張されるSynthID社会貢献のためのAIまとめはじめにGoogle主催の開発者カンファレンスGoogle I/O 2024が、日本時間2024年5月15日（アメリカ現地時間5月14日）から2日間の日程で開催されました。OpenAIがGPT-4oを発表した直後に開催された同カンファレンスでは、予想通りGoogleのAI開発に関する新情報が大量に発表されました。本記事では、Google I/O 2024で発表されたGoogleのAI技術とサービスに関する新情報をほぼ網羅的にまとめます。これらの情報はUS版Google公式ブログに設けられた「I/O 2024」関連ブログ記事集を参照したものであり、以下の各見出しの末尾には出典記事を明記します。日本語訳のある記事については、日本語訳記事を出典とします。参考記事：Google I/O 2022で発表された最新自然言語処理技術まとめAIによって自社を全方位的にアップデートしたGoogle I/O 2023まとめサマリー本記事の各見出しで解説する内容は、以下の表のようにまとめられます。見出し名キーワードGeminiファミリーのアップデートとその活用軽量なGemini 1.5 Flash、コンテキストウィンドウを200万にアップデートしたGemini 1.5 Pro、リアルタイム動画による対話を実現したProject Astra、多機能な生成検索AI Overviews、Geminiと連携するGemini for Google Workspace、Gemini 1.5 Proを採用したGemini Advanced、Geminiと対話できるGoogleメッセージ、Geminiと音声で話せるGemini LiveAIによるAndroidの進化教育用AI「LearnLM」と連携するかこって検索、Geminiと連携するオーバーレイ機能・TalkBack、Gemini Nanoの搭載、AIによる詐欺電話の検出、AIが画像を選定するAsk Photos、AIによる盗難防止・詐欺アプリ検出クリエイティブAIの進化画像編集が可能となったImageFX、最新画像生成モデルImagen 3、DJモードを追加したMusicFX、Music AI Sandboxによる音楽業界とのコラボレーション、動画生成アプリVideoFX、Soraに匹敵する動画生成モデルVeo、生成AI時代における実験的アート作品「無限な不思議の国」AI開発者のためのAI軽量かつ高性能なオープンソースモデルGemma 2、最新視覚言語オープンソースモデルPaliGemma、デロリアンが授与されるGeminiAPIデベロッパーコンペティション、AIの安全性を評価するLLM Comparator第6世代AI用ハードウェア「Trillium」前世代よりパフォーマンスが4.7倍となったTPU「Trillium」責任あるAIの取り組みテキストと動画に拡張されるSynthID、LearnLMを活用した教育アプリIlluminateとLearn about、機械学習アルゴリズムによる人間の脳の3D再構築、DNAやRNAも予測可能となったAlphaFold 3、医療に特化したMed-GeminiGeminiファミリーのアップデートとその活用Google I/O 2024においてもっとも重要な発表は、Googleが展開するAIビジネスの根幹となる基盤モデルGeminiのアップデート情報です。以下では、新しい2つのGeminiモデルとGeminiを活用したサービスとアプリをまとめます。軽量な1.5 Flash、アップデートしたGemini 1.5 Pro、先進的なProject AstraGeminiファミリーに効率性を重視したGemini 1.5 Flashが加わりました。​'

texts = [sentence]
labels = ["AI", "未来", "テクノロジー", "アーキテクチャ", "ビジネス", "スポーツ", "エンタメ"]

# 長い入力は内部でトランケイトされる模様
result_md = classifier_mDeBERT(texts, labels, hypothesis_template="このニュースは{}に関する文章です.", multi_label=True)
print(result_md[0].get("labels"))
print(result_md[0].get("scores"))



['テクノロジー', 'AI', '未来', 'アーキテクチャ', 'ビジネス', 'エンタメ', 'スポーツ']
[0.999890923500061, 0.9997818470001221, 0.9997126460075378, 0.9996882677078247, 0.9833944439888, 0.0002405198902124539, 6.651310832239687e-05]


パイプラインから実行（英語）

In [26]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1
classifier_mDeBERT = pipeline("zero-shot-classification",model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7", device=device)

sentence = 'Michael Cohen implicated his former bossDonald Trumpin the hush money scheme to pay Stormy Daniels just days before the 2016 election, saying he doled out $130,000 at Trump’s direction and was promised reimbursement.Cohen’s testimony ties together the prosecution’s allegations that Trump broke the law by falsifying business records to reimburse Cohen and conceal the hush money payment that Cohen said he made at Trump’s direction. Trump has pleaded not guilty and denies having an affair with Daniels.Related live-storyMichael Cohen testifies in Trump hush money trialCohen and Trump mostly avoided eye contact while he testified Monday. Cohen looked directly at prosecutor Susan Hoffinger throughout most of his testimony, occasionally scanning the room or looking in the jury’s direction.'
# sentence = '''On May 13, 2024, US time, US OpenAI held an online new product launch event and announced the next-generation AI (artificial intelligence) model "GPT-4o". It is a flagship model that will succeed the current model "GPT-4 turbo". The keyword is "speed". It will enable real-time dialogue between AI and voice. With OpenAI's new move, "speed" and "usability" are likely to emerge as the next competitive axis for AI models. The "o" in GPT-4o comes from the prefix "omni", which means "all". It can accept any combination of text, voice, images, etc. as input and output. What OpenAI particularly emphasized at the launch event was the improvement of voice dialogue performance. Although voice mode was available in "ChatGPT", which used conventional models such as GPT-4, there were issues with waiting time (latency). The average latency was 2.8 seconds for GPT-3.5 and 5.4 seconds for GPT-4. GPT-4o reduced this to an average of 0.32 seconds. The breakthrough was in the model's learning method. Models prior to GPT-4o supported voice mode by combining three independent models. The first model transcribed the voice as text, the second model took in the text and output the answer as text, and the third model converted the text to voice. Because it was converted to text once, it was not possible to incorporate information such as tone of voice or conversations by multiple speakers, and emotions could not be expressed as output. In contrast, GPT-4o is a model trained by combining visual information such as images and videos, text, and voice. By changing the learning method, it achieved low latency and acquired new capabilities to take emotions into account.'''

texts = [sentence]
# labels = ["AI", "未来", "テクノロジー", "アーキテクチャ", "ビジネス", "スポーツ", "エンタメ"]
labels = ["未来", "政治"]
result_md = classifier_mDeBERT(texts, labels, hypothesis_template="このニュースは{}に関する文章です.", multi_label=True)
print(result_md[0].get("labels"))
print(result_md[0].get("scores"))

['政治', '未来']
[0.9821041822433472, 0.0034678068477660418]


マニュアル操作

In [14]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch

nli_model = AutoModelForSequenceClassification.from_pretrained('facebook/bart-large-mnli')
tokenizer = AutoTokenizer.from_pretrained('facebook/bart-large-mnli')

sentence = 'Who are you voting for in 2020?'
labels = ['business', 'art & culture', 'politics']

premise = sentence
hypothesis = f'This example is {labels[2]}.' # ラベル'politics'の確率を調べる

# run through model pre-trained on MNLI
x = tokenizer.encode(premise, hypothesis, return_tensors='pt',
                     truncation_strategy='only_first')
print(tokenizer.decode(x.flatten()))
print(x)

if torch.cuda.is_available():
  x = x.cuda()
  nli_model = nli_model.cuda()

with torch.no_grad():
  logits = nli_model(x)[0]
print(logits)

# ロジットのうち、含意（entailment）のロジット（インデックス2）と矛盾（contradiction）のロジット（インデックス0）を抽出します。中立（neutral）のロジット（インデックス1）は無視します。
entail_contradiction_logits = logits[:,[0,2]]
print(entail_contradiction_logits)

# 出したロジットに対してソフトマックス関数を適用し、確率を計算します。
probs = entail_contradiction_logits.softmax(dim=1)
print(probs)

# ソフトマックス後の含意（entailment）の確率を取り出します。この確率が、ラベルが正しい確率として解釈されます。
prob_label_is_true = probs[:,1]
print(prob_label_is_true)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2734: FutureWarning: The `truncation_strategy` argument is deprecated and will be removed in a future version, use `truncation=True` to truncate examples to a max length. You can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to truncate to the maximal input size of the model (e.g. 512 for Bert).  If you have pairs of inputs, you can give a specific truncation strategy selected among `truncation='only_first'` (will only truncate the first sentence in the pairs) `truncation='only_second'` (will only truncate the second sentence in the pairs) or `truncation='longest_first'` (will iteratively remove tokens from the longest sentence in the pairs).
  warnings.warn(


<s>Who are you voting for in 2020?</s></s>This example is politics.</s>
tensor([[    0, 12375,    32,    47,  3434,    13,    11,  2760,   116,     2,
             2,   713,  1246,    16,  2302,     4,     2]])
tensor([[-2.2515,  1.2416,  1.2983]], device='cuda:0')
tensor([[-2.2515,  1.2983]], device='cuda:0')
tensor([[0.0279, 0.9721]], device='cuda:0')
tensor([0.9721], device='cuda:0')
